config/routes.rb
Rails.application.routes.draw do
  resources :my_threads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_thread.rb
class MyThread < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/my_threads_controller.rb
class MyThreadsController < ApplicationController
  before_action :set_my_thread, only: [:show, :edit, :update, :destroy]

  # GET /my_threads
  # GET /my_threads.json
  def index
    @my_threads = MyThread.all
  end

  # GET /my_threads/1
  # GET /my_threads/1.json
  def show
  end

  # GET /my_threads/new
  def new
    @my_thread = MyThread.new
  end

  # GET /my_threads/1/edit
  def edit
  end

  # POST /my_threads
  # POST /my_threads.json
  def create
    @my_thread = MyThread.new(my_thread_params)

    respond_to do |format|
      if @my_thread.save
        format.html { redirect_to @my_thread, notice: 'My thread was successfully created.' }
        format.json { render :show, status: :created, location: @my_thread }
      else
        format.html { render :new }
        format.json { render json: @my_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /my_threads/1
  # PATCH/PUT /my_threads/1.json
  def update
    respond_to do |format|
      if @my_thread.update(my_thread_params)
        format.html { redirect_to @my_thread, notice: 'My thread was successfully updated.' }
        format.json { render :show, status: :ok, location: @my_thread }
      else
        format.html { render :edit }
        format.json { render json: @my_thread.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /my_threads/1
  # DELETE /my_threads/1.json
  def destroy
    @my_thread.destroy
    respond_to do |format|
      format.html { redirect_to my_threads_url, notice: 'My thread was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_my_thread
      @my_thread = MyThread.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def my_thread_params
      params.require(:my_thread).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_threads_helper.rb
module MyThreadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/my_threads/_form.html.erb
<%= form_with(model: my_thread, local: true) do |form| %>
  <% if my_thread.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(my_thread.errors.count, "error") %> prohibited this my_thread from being saved:</h2>

      <ul>
      <% my_thread.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :my_thread_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/my_threads/edit.html.erb
<h1>Editing My Thread</h1>

<%= render 'form', my_thread: @my_thread %>

<%= link_to 'Show', @my_thread %> |
<%= link_to 'Back', my_threads_path %>

app/views/my_threads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Threads</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @my_threads.each do |my_thread| %>
      <tr>
        <td><%= my_thread.title %></td>
        <td><%= link_to 'Show', my_thread %></td>
        <td><%= link_to 'Edit', edit_my_thread_path(my_thread) %></td>
        <td><%= link_to 'Destroy', my_thread, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New My Thread', new_my_thread_path %>

app/views/my_threads/new.html.erb
<h1>New My Thread</h1>

<%= render 'form', my_thread: @my_thread %>

<%= link_to 'Back', my_threads_path %>

app/views/my_threads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @my_thread.title %>
</p>

<%= link_to 'Edit', edit_my_thread_path(@my_thread) %> |
<%= link_to 'Back', my_threads_path %>